Write-Verbose "load configuration..."
$deploymentDirectoryName = "clanx.deploy"
Write-Verbose "deploymentDirectoryName: $deploymentDirectoryName"
$githubUrl = "https://github.com/chriglburri/clanx"
Write-Verbose "githubUrl: $githubUrl"
$editorPath = "C:\Program Files\EditPlus\editplus.exe"
Write-Verbose "editorPath: $editorPath"
Write-Verbose "...config loaded."
